name:                template-cli
version:             0.0.0.0
github:              "NorfairKing/template-cli"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - envparse
  - mtl
  - optparse-applicative
  - path
  - path-io
  - text
  - yaml
  - yamlparse-applicative

executables:
  template-cli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - template-cli


tests:
  template-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - envparse
    - hspec
    - optparse-applicative
    - template-cli
    - yaml
